> **Results from the best observation experiment.**

# ‚öôÔ∏è Set-up
Loads required packages and set seaborn as plotting style

In [1]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import numpy as np

from helpers.paths import Path

sns.set()

Load data

In [3]:
# Load data
df_learn = pd.read_csv(Path.data/"citation-best-observation_learning.csv")
df_ep = pd.read_csv(Path.data/"citation-best-observation_episode.csv")

# üë®üèΩ‚Äçüè´ Learning performance

In [4]:
g = sns.relplot(data=df_learn, x="global_step", y="rollout/ep_len_mean", hue="algorithm", kind="line", col="reward_type")

,Unnamed: 0,global_step,rollout/ep_len_mean,rollout/ep_rew_mean,algorithm,reward_type,observation,run
0,0,3,3.000000,-33.444039,DSAC,sq_error,state + error,feasible-yogurt-566
1,1,4,1.000000,-32.733249,DSAC,sq_error,state + error,feasible-yogurt-566
2,2,6,2.000000,-38.085869,DSAC,sq_error,state + error,feasible-yogurt-566
3,3,7,1.000000,-35.053948,DSAC,sq_error,state + error,feasible-yogurt-566
4,4,8,1.000000,-38.840973,DSAC,sq_error,state + error,feasible-yogurt-566
...,...,...,...,...,...,...,...,...
26148,97,9576,97.714287,-2.777714,SAC,sq_error,states + ref + error,ethereal-elevator-387
26149,98,9677,97.747475,-2.757938,SAC,sq_error,states + ref + error,ethereal-elevator-387
26150,99,9778,97.779999,-2.739806,SAC,sq_error,states + ref + error,ethereal-elevator-387
26151,100,9879,97.879997,-2.530861,SAC,sq_error,states + ref + error,ethereal-elevator-387
26152,101,9980,98.680000,-2.318000,SAC,sq_error,states + ref + error,ethereal-elevator-387